version: "3.8"

services:
  web:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: dstdcie17/eagence:1.0.0
    container_name: e-agence
    restart: always
    ports:
      - "2707:2707"
    environment:
      - NODE_ENV=production
    volumes:
      - ./.env:/app/.env
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:2707"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy (like Nginx) for SSL termination
  # nginx:
  #  image: nginx:alpine
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #    - ./nginx/certs:/etc/nginx/certs
  #  depends_on:
  #    - web
